### ISSUE TITLE
Bug:Automatic connection to android.bugly.qq.com

### ISSUE THREAD

**Issue by Jorgu81** [wangqi060934/MyAndroidToolsWebsite#1]
I am using the last release and I see there is an automatic connection to the host android.bugly.qq.com
Is there a way to disable it? I do not see how to do this.

Greetings.

**Comment by wangqi060934** [comment]
I'm using bugly to collect crash report.
I will provide an option to close it.

**Comment by Jorgu81** [comment]
Ok, thanks.

**Comment by wangqi060934** [comment]
@Jorgu81 The new version 1.6.9.beta has an option to disable this behavior. (It will be effective after a restart)
Please have a try.
![image](https://user-images.githubusercontent.com/1433283/56290928-cb747700-6156-11e9-933d-e7c3bbcfc2e9.png)

**Comment by Jorgu81** [comment]
Well, I tried it with that option enabled and everything is ok.

Thanks a lot!
Keep up the good work!
